/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'LimeRCV3' 
 * Target:  'LimeRCV3-GUI' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* LVGL::LVGL&LVGL9:Essential@9.3.0 */
/*! \brief Enable LVGL */
#define RTE_GRAPHICS_LVGL
/* LVGL::LVGL&LVGL9:Libraries and Others:Lib Filesystem&FATFS@9.3.0 */
/*! \brief enable FATFS support */
#define LV_USE_FS_FATFS         1
/* LVGL::LVGL&LVGL9:Libraries and Others:Libs GIF@9.3.0 */
/*! \brief enable gif support */
#define LV_USE_GIF         1
/* LVGL::LVGL&LVGL9:Libraries and Others:Libs LODEPNG@9.3.0 */
/*! \brief enable LODEPNG decoder library */
#define LV_USE_LODEPNG          1
/* LVGL::LVGL&LVGL9:Libraries and Others:Libs sJPG@9.3.0 */
/*! \brief enable JPG + split JPG decoder library. */
#define LV_USE_TJPGD         1


#endif /* RTE_COMPONENTS_H */
